version: "3"
services:
  sanic-stage:
    container_name: sanic-stage
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      app_name: "sanic-stage"
      env: "pd"
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "9200:8000"
    working_dir: /data/home
    command: gunicorn web_server:app --workers=3 --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 --log-level=info
    environment:
      TZ: "Asia/Shanghai"
      ENV_MODE: "pd"
      COLUMNS: 80
      LOG_LEVEL: "INFO"
      DEBUG: "false"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1452
